# Generated by Django 6.0.6 on 2026-07-09 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='车型名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='路由标识')),
                ('price', models.CharField(blank=True, max_length=120, verbose_name='价格区间')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='车型标签')),
                ('heat', models.CharField(blank=True, max_length=120, verbose_name='改装热度')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='图片地址')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '车型',
                'verbose_name_plural': '车型',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('short_name', models.CharField(max_length=20, verbose_name='简称')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='车友会名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='路由标识')),
                ('member_count', models.CharField(blank=True, max_length=80, verbose_name='成员数量')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='图片地址')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '车友会',
                'verbose_name_plural': '车友会',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='活动名称')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='路由标识')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='图片地址')),
                ('meta', models.CharField(blank=True, max_length=120, verbose_name='时间地点')),
                ('count', models.CharField(blank=True, max_length=80, verbose_name='报名人数')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=180, unique=True, verbose_name='导购标题')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '导购文章',
                'verbose_name_plural': '导购文章',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='商品名称')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='路由标识')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='图片地址')),
                ('price', models.CharField(blank=True, max_length=80, verbose_name='价格')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '二手件',
                'verbose_name_plural': '二手件',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('short_name', models.CharField(max_length=20, verbose_name='简称')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='店家名称')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='路由标识')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='评分')),
                ('services', models.CharField(blank=True, max_length=180, verbose_name='服务范围')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='图片地址')),
                ('certified', models.BooleanField(default=True, verbose_name='TH 认证')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '改装店',
                'verbose_name_plural': '改装店',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=140, unique=True, verbose_name='专题标题')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='路由标识')),
                ('count', models.CharField(blank=True, max_length=80, verbose_name='内容数量')),
                ('desc', models.TextField(blank=True, verbose_name='专题简介')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=180, verbose_name='标题')),
                ('body', models.TextField(verbose_name='正文')),
                ('post_type', models.CharField(choices=[('改装进度', '改装进度'), ('聚会', '聚会'), ('店家施工', '店家施工'), ('二手市场', '二手市场')], default='改装进度', max_length=30, verbose_name='内容类型')),
                ('tone', models.CharField(default='blue', max_length=20, verbose_name='颜色标识')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='图片地址')),
                ('author', models.CharField(blank=True, max_length=120, verbose_name='作者')),
                ('time_label', models.CharField(blank=True, max_length=80, verbose_name='时间显示')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='项目进度')),
                ('specs', models.JSONField(blank=True, default=list, verbose_name='配置参数')),
                ('featured', models.BooleanField(default=False, verbose_name='首页精选')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.car', verbose_name='关联车型')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.club', verbose_name='关联车友会')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.shop', verbose_name='关联店家')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
                'ordering': ['-created_at'],
            },
        ),
    ]
