# Generated by Django 6.0.6 on 2026-07-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=180, unique=True, verbose_name='文章标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='路由标识')),
                ('category', models.CharField(choices=[('新车', '新车'), ('资讯', '资讯'), ('评测', '评测'), ('导购', '导购'), ('视频', '视频')], default='资讯', max_length=30, verbose_name='栏目')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('body', models.TextField(blank=True, verbose_name='正文')),
                ('image', models.CharField(blank=True, max_length=300, verbose_name='封面图')),
                ('author', models.CharField(default='TH 编辑部', max_length=120, verbose_name='作者')),
                ('featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.car', verbose_name='关联车型')),
            ],
            options={
                'verbose_name': '资讯文章',
                'verbose_name_plural': '资讯文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dealer_name', models.CharField(max_length=140, verbose_name='经销商名称')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='城市')),
                ('guide_price', models.CharField(blank=True, max_length=80, verbose_name='指导价')),
                ('dealer_price', models.CharField(blank=True, max_length=80, verbose_name='经销商报价')),
                ('discount', models.CharField(blank=True, max_length=120, verbose_name='优惠信息')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='联系电话')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.car', verbose_name='报价车型')),
            ],
            options={
                'verbose_name': '经销商报价',
                'verbose_name_plural': '经销商报价',
                'ordering': ['city', 'dealer_name'],
            },
        ),
    ]
