# Generated by Django 6.0.6 on 2026-07-09 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_article_dealeroffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarTrim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=160, verbose_name='车款名称')),
                ('official_price', models.CharField(blank=True, max_length=80, verbose_name='指导价')),
                ('dealer_price', models.CharField(blank=True, max_length=80, verbose_name='参考成交价')),
                ('engine', models.CharField(blank=True, max_length=120, verbose_name='发动机/动力')),
                ('horsepower', models.CharField(blank=True, max_length=80, verbose_name='最大功率')),
                ('drivetrain', models.CharField(blank=True, max_length=80, verbose_name='驱动形式')),
                ('gearbox', models.CharField(blank=True, max_length=100, verbose_name='变速箱')),
                ('acceleration', models.CharField(blank=True, max_length=80, verbose_name='0-100km/h')),
                ('fuel', models.CharField(default='汽油', max_length=80, verbose_name='能源类型')),
                ('featured', models.BooleanField(default=False, verbose_name='推荐车款')),
                ('state', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '已隐藏')], default='published', max_length=20, verbose_name='发布状态')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='community.car', verbose_name='所属车型')),
            ],
            options={
                'verbose_name': '车款配置',
                'verbose_name_plural': '车款配置',
                'ordering': ['car__name', '-featured', 'official_price', 'name'],
                'unique_together': {('car', 'name')},
            },
        ),
    ]
