# Generated by Django 6.0.6 on 2026-07-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_cartrim'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=80, verbose_name='姓名')),
                ('phone', models.CharField(max_length=40, verbose_name='手机号')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='城市')),
                ('dealer_name', models.CharField(blank=True, max_length=140, verbose_name='意向经销商')),
                ('source', models.CharField(blank=True, max_length=120, verbose_name='来源页面')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('new', '新线索'), ('contacted', '已联系'), ('closed', '已成交'), ('invalid', '无效')], default='new', max_length=20, verbose_name='跟进状态')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.car', verbose_name='意向车型')),
            ],
            options={
                'verbose_name': '询价线索',
                'verbose_name_plural': '询价线索',
                'ordering': ['-created_at'],
            },
        ),
    ]
