# Generated by Django 6.0.6 on 2026-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_dealerlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='articles/', verbose_name='上传封面图'),
        ),
        migrations.AddField(
            model_name='car',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='cars/', verbose_name='上传图片'),
        ),
        migrations.AddField(
            model_name='club',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='clubs/', verbose_name='上传图片'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='events/', verbose_name='上传图片'),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='market/', verbose_name='上传图片'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='posts/', verbose_name='上传图片'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image_upload',
            field=models.FileField(blank=True, upload_to='shops/', verbose_name='上传图片'),
        ),
    ]
