# Generated by Django 6.0.6 on 2026-07-13 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_article_image_upload_car_image_upload_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('nickname', models.CharField(blank=True, max_length=80, verbose_name='昵称')),
                ('avatar', models.FileField(blank=True, upload_to='avatars/', verbose_name='头像')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='等级')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='粉丝数')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='关注数')),
                ('signature', models.CharField(blank=True, max_length=160, verbose_name='个人签名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料',
                'ordering': ['user__username'],
            },
        ),
    ]
