# Generated by Django 6.0.6 on 2026-07-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_privatemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
    ]
