# Generated by Django 6.0.6 on 2026-07-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_remove_userprofile_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='作者'),
        ),
    ]
