# Generated by Django 6.0.6 on 2026-07-13 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_userdailyactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGarageVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('custom_name', models.CharField(blank=True, max_length=120, verbose_name='车辆名称')),
                ('year', models.CharField(blank=True, max_length=20, verbose_name='年份')),
                ('color', models.CharField(blank=True, max_length=40, verbose_name='颜色')),
                ('mods', models.TextField(blank=True, verbose_name='改装清单')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garage_vehicles', to='community.car', verbose_name='车型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '车库车辆',
                'verbose_name_plural': '车库车辆',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=160, verbose_name='记录标题')),
                ('stage', models.CharField(blank=True, max_length=80, verbose_name='阶段')),
                ('content', models.TextField(blank=True, verbose_name='记录内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_records', to='community.usergaragevehicle', verbose_name='车库车辆')),
            ],
            options={
                'verbose_name': '项目车记录',
                'verbose_name_plural': '项目车记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
