# Generated by Django 6.0.6 on 2026-07-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_usergaragevehicle_projectcarrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='封禁时间'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banned_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='封禁原因'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='已封禁'),
        ),
    ]
