# Generated by Django 6.0.6 on 2026-07-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_userprofile_banned_at_userprofile_banned_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='位置'),
        ),
    ]
