# Generated by Django 6.0.6 on 2026-07-17 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_content_captions_and_pinning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_articles', to=settings.AUTH_USER_MODEL, verbose_name='发布用户'),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('车主故事', '车主故事'), ('长期用车', '长期用车'), ('改装案例', '改装案例'), ('资讯', '资讯'), ('评测', '评测'), ('导购', '导购'), ('视频', '视频')], default='车主故事', max_length=30, verbose_name='栏目'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=180, verbose_name='文章标题'),
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_records', to='community.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('block_type', models.CharField(choices=[('paragraph', '正文段落'), ('heading', '小标题'), ('image', '正文图片')], max_length=20, verbose_name='内容类型')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('text', models.TextField(blank=True, verbose_name='文字内容')),
                ('image_upload', models.FileField(blank=True, upload_to='article_blocks/', verbose_name='正文图片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='图片说明')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='community.article', verbose_name='文章')),
            ],
            options={
                'verbose_name': '文章内容块',
                'verbose_name_plural': '文章内容块',
                'ordering': ['position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('article', 'position'), name='unique_article_block_position')],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_relations', to='community.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_articles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章点赞',
                'verbose_name_plural': '文章点赞',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_like')],
            },
        ),
        migrations.CreateModel(
            name='ArticleSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='community.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章收藏',
                'verbose_name_plural': '文章收藏',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'article'), name='unique_user_article_save')],
            },
        ),
    ]
