# Generated by Django 6.0.6 on 2026-07-18 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_dedupe_and_split_long_articles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('target_type', models.CharField(choices=[('article', '文章'), ('post', '动态')], max_length=20, verbose_name='内容类型')),
                ('target_id', models.PositiveIntegerField(verbose_name='内容编号')),
                ('target_title', models.CharField(max_length=180, verbose_name='内容标题')),
                ('reason', models.CharField(choices=[('不实或误导', '不实或误导'), ('广告或诈骗', '广告或诈骗'), ('侵权或盗用', '侵权或盗用'), ('辱骂或骚扰', '辱骂或骚扰'), ('危险或违法内容', '危险或违法内容'), ('其他', '其他')], max_length=30, verbose_name='举报原因')),
                ('detail', models.TextField(blank=True, verbose_name='补充说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('dismissed', '不予处理')], default='pending', max_length=20, verbose_name='处理状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报用户')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content_reports', to=settings.AUTH_USER_MODEL, verbose_name='处理管理员')),
            ],
            options={
                'verbose_name': '内容举报',
                'verbose_name_plural': '内容举报',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'target_type', 'target_id'), name='unique_user_content_report')],
            },
        ),
    ]
