# Generated by Django 6.0.6 on 2026-07-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_contentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='移入回收站时间'),
        ),
    ]
